server:
  port: 8761
spring:
  application:
   name: SERVICE-REGISTER-CENTER
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
